version: "3.5"
x-services-volume: &services-volume
  type: bind

services:
  # nginx:
  #   container_name: nginx
  #   build:
  #     context: ./nginx
  #   restart: always
  #   hostname: nginx
  #   networks:
  #     - docker_network
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - /etc/letsencrypt:/etc/letsencrypt
  #     - /home/data/certbot/www:/var/www/certbot
  #   environment:
  #     PrimaryDomain: ${PrimaryDomain}
  #   depends_on:
  #     - node
  node:
    container_name: node
    image: aglide100/ds-landing-page:latest
    hostname: node
    networks:
      - docker_network
    ports:
      - "80:3000"
    # expose:
    #   - 3000

networks:
  docker_network:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"
    ipam:
      driver: default
