name: "Deploy at server"

on:
  push:
    branches:
      - master

jobs:
  build-docker-images:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: aglide100
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./ui/
          file: ./Dockerfile
          push: true
          tags: aglide100/ds-landing-page:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: ssh scp ssh pipelines
        uses: cross-the-world/ssh-scp-ssh-pipelines@latest
        env:
          WELCOME: "ssh scp ssh pipelines"
          LASTSSH: "Doing something after copying"
        with:
          host: ${{ secrets.DC_HOST }}
          user: ${{ secrets.DC_USER }}
          #pass: ${{ secrets.DC_PASS }}
          port: ${{ secrets.DC_PORT }}
          key: ${{ secrets.DC_KEY }}
          connect_timeout: 10s
          first_ssh: |
            pwd
          scp: |
            './*' => ${{ secrets.PATH }}
          last_ssh: |
            cd ${{ secrets.PATH }}
            ./buildAndRun.sh
